match  $contract isa contract,    has contractID "1";  $rf isa risk-factor,    has risk-factor-name "contingency";  $rc isa risk-mitigation-clause,     has risk-factor-name "contingency";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "7";  $rf isa risk-factor,    has risk-factor-name "cost_of_living_adjustment";  $rc isa risk-mitigation-clause,     has risk-factor-name "cost_of_living_adjustment";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "8";  $rf isa risk-factor,    has risk-factor-name "contingency";  $rc isa risk-mitigation-clause,     has risk-factor-name "contingency";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "6";  $rf isa risk-factor,    has risk-factor-name "expenses";  $rc isa risk-mitigation-clause,     has risk-factor-name "expenses";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "8";  $rf isa risk-factor,    has risk-factor-name "expenses";  $rc isa risk-mitigation-clause,     has risk-factor-name "expenses";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "10";  $rf isa risk-factor,    has risk-factor-name "cost_of_living_adjustment";  $rc isa risk-mitigation-clause,     has risk-factor-name "cost_of_living_adjustment";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "19";  $rf isa risk-factor,    has risk-factor-name "jurisdiction";  $rc isa risk-mitigation-clause,     has risk-factor-name "jurisdiction";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "19";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "13";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "11";  $rf isa risk-factor,    has risk-factor-name "cost_of_living_adjustment";  $rc isa risk-mitigation-clause,     has risk-factor-name "cost_of_living_adjustment";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "9";  $rf isa risk-factor,    has risk-factor-name "cost_of_living_adjustment";  $rc isa risk-mitigation-clause,     has risk-factor-name "cost_of_living_adjustment";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "14";  $rf isa risk-factor,    has risk-factor-name "cost_of_living_adjustment";  $rc isa risk-mitigation-clause,     has risk-factor-name "cost_of_living_adjustment";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "16";  $rf isa risk-factor,    has risk-factor-name "termination";  $rc isa risk-mitigation-clause,     has risk-factor-name "termination";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "5";  $rf isa risk-factor,    has risk-factor-name "termination";  $rc isa risk-mitigation-clause,     has risk-factor-name "termination";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "0";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "2";  $rf isa risk-factor,    has risk-factor-name "jurisdiction";  $rc isa risk-mitigation-clause,     has risk-factor-name "jurisdiction";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "13";  $rf isa risk-factor,    has risk-factor-name "cost_of_living_adjustment";  $rc isa risk-mitigation-clause,     has risk-factor-name "cost_of_living_adjustment";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "11";  $rf isa risk-factor,    has risk-factor-name "termination";  $rc isa risk-mitigation-clause,     has risk-factor-name "termination";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "5";  $rf isa risk-factor,    has risk-factor-name "contingency";  $rc isa risk-mitigation-clause,     has risk-factor-name "contingency";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "4";  $rf isa risk-factor,    has risk-factor-name "expenses";  $rc isa risk-mitigation-clause,     has risk-factor-name "expenses";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "6";  $rf isa risk-factor,    has risk-factor-name "jurisdiction";  $rc isa risk-mitigation-clause,     has risk-factor-name "jurisdiction";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "8";  $rf isa risk-factor,    has risk-factor-name "cost_of_living_adjustment";  $rc isa risk-mitigation-clause,     has risk-factor-name "cost_of_living_adjustment";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "7";  $rf isa risk-factor,    has risk-factor-name "jurisdiction";  $rc isa risk-mitigation-clause,     has risk-factor-name "jurisdiction";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "10";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "15";  $rf isa risk-factor,    has risk-factor-name "contingency";  $rc isa risk-mitigation-clause,     has risk-factor-name "contingency";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "17";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "1";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "0";  $rf isa risk-factor,    has risk-factor-name "contingency";  $rc isa risk-mitigation-clause,     has risk-factor-name "contingency";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "16";  $rf isa risk-factor,    has risk-factor-name "jurisdiction";  $rc isa risk-mitigation-clause,     has risk-factor-name "jurisdiction";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "6";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "9";  $rf isa risk-factor,    has risk-factor-name "jurisdiction";  $rc isa risk-mitigation-clause,     has risk-factor-name "jurisdiction";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "16";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "2";  $rf isa risk-factor,    has risk-factor-name "termination";  $rc isa risk-mitigation-clause,     has risk-factor-name "termination";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "15";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "14";  $rf isa risk-factor,    has risk-factor-name "expenses";  $rc isa risk-mitigation-clause,     has risk-factor-name "expenses";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "18";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "6";  $rf isa risk-factor,    has risk-factor-name "contingency";  $rc isa risk-mitigation-clause,     has risk-factor-name "contingency";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "12";  $rf isa risk-factor,    has risk-factor-name "termination";  $rc isa risk-mitigation-clause,     has risk-factor-name "termination";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "18";  $rf isa risk-factor,    has risk-factor-name "cost_of_living_adjustment";  $rc isa risk-mitigation-clause,     has risk-factor-name "cost_of_living_adjustment";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "17";  $rf isa risk-factor,    has risk-factor-name "expenses";  $rc isa risk-mitigation-clause,     has risk-factor-name "expenses";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "13";  $rf isa risk-factor,    has risk-factor-name "contingency";  $rc isa risk-mitigation-clause,     has risk-factor-name "contingency";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "8";  $rf isa risk-factor,    has risk-factor-name "termination";  $rc isa risk-mitigation-clause,     has risk-factor-name "termination";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "4";  $rf isa risk-factor,    has risk-factor-name "jurisdiction";  $rc isa risk-mitigation-clause,     has risk-factor-name "jurisdiction";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "11";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "14";  $rf isa risk-factor,    has risk-factor-name "termination";  $rc isa risk-mitigation-clause,     has risk-factor-name "termination";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "10";  $rf isa risk-factor,    has risk-factor-name "jurisdiction";  $rc isa risk-mitigation-clause,     has risk-factor-name "jurisdiction";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "12";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "11";  $rf isa risk-factor,    has risk-factor-name "jurisdiction";  $rc isa risk-mitigation-clause,     has risk-factor-name "jurisdiction";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "6";  $rf isa risk-factor,    has risk-factor-name "cost_of_living_adjustment";  $rc isa risk-mitigation-clause,     has risk-factor-name "cost_of_living_adjustment";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "7";  $rf isa risk-factor,    has risk-factor-name "contingency";  $rc isa risk-mitigation-clause,     has risk-factor-name "contingency";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "4";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "9";  $rf isa risk-factor,    has risk-factor-name "termination";  $rc isa risk-mitigation-clause,     has risk-factor-name "termination";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "8";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "11";  $rf isa risk-factor,    has risk-factor-name "expenses";  $rc isa risk-mitigation-clause,     has risk-factor-name "expenses";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "1";  $rf isa risk-factor,    has risk-factor-name "jurisdiction";  $rc isa risk-mitigation-clause,     has risk-factor-name "jurisdiction";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "2";  $rf isa risk-factor,    has risk-factor-name "foreign_exchange";  $rc isa risk-mitigation-clause,     has risk-factor-name "foreign_exchange";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "18";  $rf isa risk-factor,    has risk-factor-name "jurisdiction";  $rc isa risk-mitigation-clause,     has risk-factor-name "jurisdiction";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "19";  $rf isa risk-factor,    has risk-factor-name "cost_of_living_adjustment";  $rc isa risk-mitigation-clause,     has risk-factor-name "cost_of_living_adjustment";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "19";  $rf isa risk-factor,    has risk-factor-name "contingency";  $rc isa risk-mitigation-clause,     has risk-factor-name "contingency";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "3";  $rf isa risk-factor,    has risk-factor-name "cost_of_living_adjustment";  $rc isa risk-mitigation-clause,     has risk-factor-name "cost_of_living_adjustment";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "0";  $rf isa risk-factor,    has risk-factor-name "termination";  $rc isa risk-mitigation-clause,     has risk-factor-name "termination";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
match  $contract isa contract,    has contractID "2";  $rf isa risk-factor,    has risk-factor-name "cost_of_living_adjustment";  $rc isa risk-mitigation-clause,     has risk-factor-name "cost_of_living_adjustment";insert  $contract-risk (contract-has: $contract, contract-risk-factor: $rf) isa contract-risk;  $contract-mitigation (contract-has: $contract, contract-mitigation-clause: $rc) isa contract-mitigation;
